name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enable wasm32-wasi
        run: |
          rustup target add wasm32-wasip1
      - name: install wasmedge
        run: |
          curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- -v 0.14.1
      - name: build wasm
        run: |
          cargo build --release --target wasm32-wasip1
      - name: test
        run: |
          go mod download github.com/second-state/wasmedge-bindgen
          go mod download github.com/second-state/WasmEdge-go
          go run main.go
